services:
  db:
    image: postgres
    container_name: rental_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rental_db
      POSTGRES_USER: rental_user
      POSTGRES_PASSWORD: rental_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: